version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-cdc
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: >
      --server-id=1
      --log-bin=mysql-bin
      --binlog-format=ROW
      --binlog-row-image=FULL
      --enforce-gtid-consistency=ON
      --gtid-mode=ON
    networks:
      - cdc-network

volumes:
  mysql_data:

networks:
  cdc-network:
    external: true
